 
name: build-check

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
      
jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: 
          - fqbn: "arduino:avr:uno"
            multiSerial: false
            platform-name: arduino:avr
          - fqbn: "Infineon:xmc:XMC1100_XMC2GO"
            multiSerial: false
            platform-name: Infineon:xmc
          - fqbn: "Infineon:xmc:XMC1100_Boot_Kit"
            multiSerial: false
            platform-name: Infineon:xmc
          - fqbn: "esp32:esp32:featheresp32"
            multiSerial: true
            platform-name: esp32:esp32
          - fqbn: "arduino:renesas_uno:unor4wifi"
            multiSerial: true
            platform-name: arduino:renesas_uno

        include:
          - board:
              platform-name: arduino:avr
              multiSerial: false
            multiserial-sketch-paths: |
              - 
            platforms: |
              # Install Arduino Avr Boards via Boards Manager
              - name: arduino:avr
              
          - board:
              platform-name: Infineon:xmc
            platforms: |
              # Install Arduino Avr Boards via Boards Manager
              - name: Infineon:xmc
                source-url: https://github.com/Infineon/XMC-for-Arduino/releases/latest/download/package_infineon_index.json
                
          - board:
              platform-name: esp32:esp32
            platforms: |
              # Install ESP32 platform via Boards Manager
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          - board:
              platform-name: arduino:renesas_uno
            platforms: |
              # Install Arduino UNO R4 WiFi via Boards Manager
              - name: arduino:renesas_uno
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build examples 
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          if: 
          sketches: | 
            matrix.board.multiserial ?"examples/continuous-mode-uart":
              "example/alarm-notification
               example/continuous-mode
               example/device-id
               example/early-notification
               example/forced-compensation
               example/single-shot-mode"

              