 
name: build-check

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
      
jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    strategy:
    
      matrix:
        board: 
          - fqbn: arduino:avr:uno
          - fqbn: Infineon:arm:XMC1100_XMC2GO
          - fqbn: Infineon:arm:XMC1100_Boot_Kit

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build examples 
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: |
            - name: Infineon:arm
              source-url: https://github.com/Infineon/XMC-for-Arduino/releases/latest/download/package_infineon_index.json
            - source-path: "."
              name: Infineon:arm
              
            - name: arduino:avr
            - source-path: "."
              name: arduino:avr
              