 
name: build-check

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
      
jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: 
          - fqbn: "arduino:avr:uno"
            platform-name: arduino:avr
          - fqbn: "Infineon:arm:XMC1100_XMC2GO"
            platform-name: Infineon:arm
          - fqbn: "Infineon:arm:XMC1100_Boot_Kit"
            platform-name: Infineon:arm
          - fqbn: "esp32:esp32:featheresp32"
            platform-name: esp32:esp32

        include:
          - board:
              platform-name: arduino:avr
            platforms: |
              # Install Arduino Avr Boards via Boards Manager
              - name: arduino:avr
              
          - board:
              platform-name: Infineon:arm
            platforms: |
              # Install Arduino Avr Boards via Boards Manager
              - name: Infineon:arm
                source-url: https://github.com/Infineon/XMC-for-Arduino/releases/latest/download/package_infineon_index.json
                
          - board:
              platform-name: esp32:esp32
            platforms: |
              # Install ESP32 platform via Boards Manager
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build examples 
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}

              